packages:
  - "packages/eko-core"
  - "packages/eko-extension"
  - "packages/eko-nodejs"
  - "packages/eko-web"
  - "packages/eko-debugger"
  - "example/nodejs"
  - "example/nodejs_debug"
  - "example/extension"
  - "example/web"
